# Template Sync workflow for hvd modules. This workflow is invoked from workflows in the hvd module repos.
name: Template Sync

on:
  workflow_call:
permissions:
  contents: write
  pull-requests: write

jobs:
    repo-sync:
      runs-on: ubuntu-latest
      permissions:
        contents: write
        pull-requests: write

      steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@8a0f668b83c32a0f673353086d74f12b8853d4f5 # v2.5.3
        with:
          source_repo_path: hashicorp/hvd-module-template
          upstream_branch: main
          pr_labels: template_sync

